[package]
name = "baytowne/viewportmodel"
description = "Lua class to calculate camera distance/cframe for fitting models into viewport frames."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"